title: "INFO 4340"
tagline: "Analytics and AI"
baseurl: "/info4340"
url: "https://steflangehennig.github.io"

instructor: "Stefani Langehennig, PhD"
term: "Fall 2026"
meeting: "Monday/Wednesday 8:00 - 9:50 PM"
location: "DCB 100"
office_hours: "Monday 2:00 - 4:00 PM or by appointment"
contact: "stefani.langehennig@du.edu"

nav:
  - title: "Syllabus"
    url: /syllabus/
  - title: "Schedule"
    url: /schedule/
  - title: "Guides"
    url: /guides/
  - title: "Assignments"
    url: /assignments/

markdown: kramdown
permalink: pretty
